/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MultiSigWalletInterface extends ethers.utils.Interface {
  functions: {
    "confirmTransaction(uint256)": FunctionFragment;
    "executeTransaction(uint256)": FunctionFragment;
    "getOwners()": FunctionFragment;
    "getTransaction(uint256)": FunctionFragment;
    "getTransactionCount()": FunctionFragment;
    "isConfirmed(uint256,address)": FunctionFragment;
    "isOwner(address)": FunctionFragment;
    "numConfirmationsRequired()": FunctionFragment;
    "owners(uint256)": FunctionFragment;
    "revokeConfirmation(uint256)": FunctionFragment;
    "submitTransaction(address,uint256,bytes)": FunctionFragment;
    "transactions(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "confirmTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getOwners", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isConfirmed",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "numConfirmationsRequired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "owners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeConfirmation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTransaction",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confirmTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConfirmed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numConfirmationsRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeConfirmation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;

  events: {
    "ConfirmTransaction(address,uint256)": EventFragment;
    "Deposit(address,uint256,uint256)": EventFragment;
    "ExecuteTransaction(address,uint256)": EventFragment;
    "RevokeConfirmation(address,uint256)": EventFragment;
    "SubmitTransaction(address,uint256,address,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConfirmTransaction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecuteTransaction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevokeConfirmation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SubmitTransaction"): EventFragment;
}

export class MultiSigWallet extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MultiSigWalletInterface;

  functions: {
    confirmTransaction(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "confirmTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    executeTransaction(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getOwners(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    "getOwners()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    getTransaction(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      to: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      numConfirmations: BigNumber;
      0: string;
      1: BigNumber;
      2: string;
      3: boolean;
      4: BigNumber;
    }>;

    "getTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      to: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      numConfirmations: BigNumber;
      0: string;
      1: BigNumber;
      2: string;
      3: boolean;
      4: BigNumber;
    }>;

    getTransactionCount(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getTransactionCount()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    isConfirmed(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isConfirmed(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    isOwner(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isOwner(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    numConfirmationsRequired(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "numConfirmationsRequired()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    owners(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    revokeConfirmation(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revokeConfirmation(uint256)"(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    submitTransaction(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "submitTransaction(address,uint256,bytes)"(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      to: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      numConfirmations: BigNumber;
      0: string;
      1: BigNumber;
      2: string;
      3: boolean;
      4: BigNumber;
    }>;

    "transactions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      to: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      numConfirmations: BigNumber;
      0: string;
      1: BigNumber;
      2: string;
      3: boolean;
      4: BigNumber;
    }>;
  };

  confirmTransaction(
    _txIndex: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "confirmTransaction(uint256)"(
    _txIndex: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  executeTransaction(
    _txIndex: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeTransaction(uint256)"(
    _txIndex: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getOwners(overrides?: CallOverrides): Promise<string[]>;

  "getOwners()"(overrides?: CallOverrides): Promise<string[]>;

  getTransaction(
    _txIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    to: string;
    value: BigNumber;
    data: string;
    executed: boolean;
    numConfirmations: BigNumber;
    0: string;
    1: BigNumber;
    2: string;
    3: boolean;
    4: BigNumber;
  }>;

  "getTransaction(uint256)"(
    _txIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    to: string;
    value: BigNumber;
    data: string;
    executed: boolean;
    numConfirmations: BigNumber;
    0: string;
    1: BigNumber;
    2: string;
    3: boolean;
    4: BigNumber;
  }>;

  getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;

  "getTransactionCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  isConfirmed(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isConfirmed(uint256,address)"(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isOwner(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "isOwner(address)"(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  numConfirmationsRequired(overrides?: CallOverrides): Promise<BigNumber>;

  "numConfirmationsRequired()"(overrides?: CallOverrides): Promise<BigNumber>;

  owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "owners(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  revokeConfirmation(
    _txIndex: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revokeConfirmation(uint256)"(
    _txIndex: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  submitTransaction(
    _to: string,
    _value: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "submitTransaction(address,uint256,bytes)"(
    _to: string,
    _value: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transactions(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    to: string;
    value: BigNumber;
    data: string;
    executed: boolean;
    numConfirmations: BigNumber;
    0: string;
    1: BigNumber;
    2: string;
    3: boolean;
    4: BigNumber;
  }>;

  "transactions(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    to: string;
    value: BigNumber;
    data: string;
    executed: boolean;
    numConfirmations: BigNumber;
    0: string;
    1: BigNumber;
    2: string;
    3: boolean;
    4: BigNumber;
  }>;

  callStatic: {
    confirmTransaction(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "confirmTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    executeTransaction(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getOwners(overrides?: CallOverrides): Promise<string[]>;

    "getOwners()"(overrides?: CallOverrides): Promise<string[]>;

    getTransaction(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      to: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      numConfirmations: BigNumber;
      0: string;
      1: BigNumber;
      2: string;
      3: boolean;
      4: BigNumber;
    }>;

    "getTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      to: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      numConfirmations: BigNumber;
      0: string;
      1: BigNumber;
      2: string;
      3: boolean;
      4: BigNumber;
    }>;

    getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;

    "getTransactionCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    isConfirmed(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isConfirmed(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isOwner(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "isOwner(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    numConfirmationsRequired(overrides?: CallOverrides): Promise<BigNumber>;

    "numConfirmationsRequired()"(overrides?: CallOverrides): Promise<BigNumber>;

    owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "owners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    revokeConfirmation(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeConfirmation(uint256)"(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    submitTransaction(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "submitTransaction(address,uint256,bytes)"(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      to: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      numConfirmations: BigNumber;
      0: string;
      1: BigNumber;
      2: string;
      3: boolean;
      4: BigNumber;
    }>;

    "transactions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      to: string;
      value: BigNumber;
      data: string;
      executed: boolean;
      numConfirmations: BigNumber;
      0: string;
      1: BigNumber;
      2: string;
      3: boolean;
      4: BigNumber;
    }>;
  };

  filters: {
    ConfirmTransaction(
      owner: string | null,
      txIndex: BigNumberish | null
    ): EventFilter;

    Deposit(sender: string | null, amount: null, balance: null): EventFilter;

    ExecuteTransaction(
      owner: string | null,
      txIndex: BigNumberish | null
    ): EventFilter;

    RevokeConfirmation(
      owner: string | null,
      txIndex: BigNumberish | null
    ): EventFilter;

    SubmitTransaction(
      owner: string | null,
      txIndex: BigNumberish | null,
      to: string | null,
      value: null,
      data: null
    ): EventFilter;
  };

  estimateGas: {
    confirmTransaction(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "confirmTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    executeTransaction(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getOwners(overrides?: CallOverrides): Promise<BigNumber>;

    "getOwners()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTransaction(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;

    "getTransactionCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    isConfirmed(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isConfirmed(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOwner(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isOwner(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numConfirmationsRequired(overrides?: CallOverrides): Promise<BigNumber>;

    "numConfirmationsRequired()"(overrides?: CallOverrides): Promise<BigNumber>;

    owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "owners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revokeConfirmation(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "revokeConfirmation(uint256)"(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    submitTransaction(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "submitTransaction(address,uint256,bytes)"(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "transactions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    confirmTransaction(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "confirmTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    executeTransaction(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getOwners(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getOwners()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTransaction(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTransaction(uint256)"(
      _txIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTransactionCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTransactionCount()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isConfirmed(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isConfirmed(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOwner(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isOwner(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numConfirmationsRequired(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "numConfirmationsRequired()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owners(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "owners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revokeConfirmation(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revokeConfirmation(uint256)"(
      _txIndex: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    submitTransaction(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "submitTransaction(address,uint256,bytes)"(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "transactions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
